### ISSUE TITLE
[Question]GPU Installation of vis_cpu

### ISSUE THREAD

**Issue by JianrongTan** [HERA-Team/vis_cpu#23]
I tried `pip install vis_cpu.[gpu]` to install the gpu functions, while it failed in my terminal with the error message 

> ERROR: Invalid requirement: 'vis_cpu.[gpu]' 

I wonder what should be the correct way here to install those functions.

**Comment by steven-murray** [comment]
Hi @JianrongTan, I htink the command should b` pip install vis_cpu[gpu]` (i.e. no dot)

**Comment by JianrongTan** [comment]
Thanks @steven-murray! I just copy the command (with dot) from `README.rst`. Maybe it could also get fixed there.
