### ISSUE TITLE
[Feature Req] Possibility of including a C version of the core loop

### ISSUE THREAD

**Issue by steven-murray** [HERA-Team/vis_cpu#34]
**Is your feature request related to a problem? Please describe.**
The core loop in vis_cpu is obviously going to be the bottleneck for large numbers of sources/times. It is unclear if this could be sped up a lot or a little by rewriting it in C, but if it can be sped up, it might be worth trying it out. It should not be hard, either.

**Describe the solution you'd like**
I'd like to see a single C function wrapped with something like CFFI/ctypes that does the core loop, and uses memory/cpu well.

**Describe alternatives you've considered**
We could write this with numba, or Cython. I prefer plain C, but others can interject here. One difficulty (not a huge one) would be the 2D interpolation. Another would be that even including any C means that it's not pure python and maintenance/installation is more difficult and platform dependent. I'd recommend making it *optional* to use the C loop (similar to the way the GPU is optional).

**Comment by steven-murray** [comment]
I think that, since the main bottleneck for realistically large arrays is the vis*vis matrix product, which is BLAS-optimized, a C-loop wouldn't be very helpful here.

**Comment by mkolopanis** [comment]
Weird showing up late to this thread, but @rlbyrne and I has been using matvis to simulate OVRO-LWA. 
She in particular has noticed CPU using being a steady 100% over most of the simulation time.

**Comment by steven-murray** [comment]
@mkolopanis I'm trying to read into what you're saying -- are you saying that a C-loop might then offer more speed, or that we've already hit max speed?

**Comment by mkolopanis** [comment]
I think what I'm saying is that a loop in another language may indeed help.  Ruby was seeing that her computations were just using 1 core for the most time spent during a simulation. But need to figure out where to identify what could be the bottleneck.
